# SYSTEM
url: "https://hci-calendar.github.io"
baseurl: ""

# SITE
title: HCI Calendar

description: >-
  HCI Calendar helps you to find the timely conference for your research.

message1: >-
  Please check correct information on the conference website.

message2: >-
  This site provides last dates posted on our database.<br/>
  You can help us to edit on <a href="https://github.com/hci-calendar/hci-calendar.github.io">GitHub</a>.

keywords: >-
  HCI Calendar,
  academic, research, technology, computer science,
  HCI, Human Computer Interaction,
  VR, Virtual Reality,
  CG, Computer graphics,

copyright: "Copyright (C) HCI Calendar. All rights reserved."

# INCLUDE PAGES
include: ['_pages']

sass:
  sass_dir: ./_sass

plugins:
  - jekyll-redirect-from
